# Generated by Django 3.1.7 on 2021-03-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMediaApp', '0015_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
