# Generated by Django 3.1.7 on 2021-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMediaApp', '0021_auto_20210318_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoin',
            name='accept',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
